package estu.ceng.entities.concrete;

public enum Category {
    BREAKFAST, LUNCH, DINNER, DESSERT, APPETIZER, SNACK, DRINK, SALAD, SOUP, SAUCE, SIDE_DISH, BREAD, PASTA, MEAT, SEAFOOD, VEGETABLE, FRUIT, SPICE, CONDIMENTS, BEVERAGE, NONE

}
